// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY6zi23ydVv2a0cVeunkw6dojb38nAC1E',
    appId: '1:384150602111:web:f48f84ef1b0256ef945a4a',
    messagingSenderId: '384150602111',
    projectId: 'habishare-dev-677f8',
    authDomain: 'habishare-dev-677f8.firebaseapp.com',
    storageBucket: 'habishare-dev-677f8.firebasestorage.app',
    measurementId: 'G-CSSTNT9Y4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpE8XJZNq91BdJGpOCg34qbR0rtRWQcOM',
    appId: '1:384150602111:android:e9cd53bb64e30eae945a4a',
    messagingSenderId: '384150602111',
    projectId: 'habishare-dev-677f8',
    storageBucket: 'habishare-dev-677f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcdONm6POQZHq0nLMvcr8iuqMDWi8nnhg',
    appId: '1:384150602111:ios:d07adc30907a19c8945a4a',
    messagingSenderId: '384150602111',
    projectId: 'habishare-dev-677f8',
    storageBucket: 'habishare-dev-677f8.firebasestorage.app',
    iosBundleId: 'com.example.habiShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcdONm6POQZHq0nLMvcr8iuqMDWi8nnhg',
    appId: '1:384150602111:ios:d07adc30907a19c8945a4a',
    messagingSenderId: '384150602111',
    projectId: 'habishare-dev-677f8',
    storageBucket: 'habishare-dev-677f8.firebasestorage.app',
    iosBundleId: 'com.example.habiShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY6zi23ydVv2a0cVeunkw6dojb38nAC1E',
    appId: '1:384150602111:web:0cf9274f18fc6746945a4a',
    messagingSenderId: '384150602111',
    projectId: 'habishare-dev-677f8',
    authDomain: 'habishare-dev-677f8.firebaseapp.com',
    storageBucket: 'habishare-dev-677f8.firebasestorage.app',
    measurementId: 'G-E4RFZRGWNH',
  );
}
